import { Book } from "./interface";

export const books: Book[] = [
  {
    id: "2",
    title: "Mathematics XII",
    author: "Michael Chen",
    description:
      "A comprehensive math textbook covering advanced topics for grade XII students, designed to strengthen problem-solving and analytical skills.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/476138304.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/856169633.pdf",
    category: "Mathematics",
    level: "XII",
    pages: 245,
    rating: 4.6,
    reviews: 892,
    isPaid: false,
    price: 0,
    downloadCount: 3450,
    uploadedDate: "2024-02-01",
  },
  {
    id: "3",
    title: "Chemistry XII",
    author: "Emma Wilson",
    description:
      "A complete chemistry guide for grade XII students covering organic, inorganic, and physical chemistry with detailed explanations and exercises.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/1793776781.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/750475257.pdf",
    category: "Chemistry",
    level: "XII",
    pages: 312,
    rating: 4.9,
    reviews: 1203,
    isPaid: false,
    price: 0,
    downloadCount: 8900,
    uploadedDate: "2024-01-08",
  },
  {
    id: "4",
    title: "IELTS Preparation 2024",
    author: "British Council",
    description:
      "A complete IELTS preparation guide with practice tests, expert strategies, and examiner tips to help you achieve your desired band score.",
    coverImage: "/api/placeholder/300/400",
    pdfUrl: "/pdfs/ielts-preparation-2024.pdf",
    category: "Exam Preparation",
    level: "Advanced",
    pages: 456,
    rating: 4.7,
    reviews: 2312,
    isPaid: true,
    price: 499,
    downloadCount: 5670,
    uploadedDate: "2024-01-20",
  },
  {
    id: "5",
    title: "English XI",
    author: "Lisa Thompson",
    description:
      "Practical examples and reading materials designed to enhance vocabulary, comprehension, and grammar for grade XI students.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/2032304972.JPG",
    pdfUrl: "/pdfs/everyday-english-conversations.pdf",
    category: "English",
    level: "XI",
    pages: 189,
    rating: 4.5,
    reviews: 678,
    isPaid: false,
    price: 0,
    downloadCount: 7230,
    uploadedDate: "2024-02-10",
  },
  {
    id: "6",
    title: "Gulzar-E-Urdu XII",
    author: "Prof. James Miller",
    description:
      "An Urdu literature book for grade XII featuring poetry, prose, and grammar lessons to develop a deeper understanding of Urdu language and culture.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/470596573.jpg",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/779539258.pdf",
    category: "Urdu",
    level: "XII",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
    
  },
  {
    id: "7",
    title: "Physics XII",
    author: "Prof. James Miller",
    description:"Covers all essential physics topics for grade XII, including mechanics, optics, and electromagnetism, with examples and solved problems.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/2112649985.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1240771973.pdf",
    category: "Physics",
    level: "XII",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "8",
    title: "Biology XII",
    author: "Prof. James Miller",
    description:"Detailed biology book for grade XII covering human anatomy, genetics, evolution, and plant sciences with diagrams and exercises.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/319808494.png",
    pdfUrl: "/pdfs/academic-writing-skills.pdf",
    category: "Biology",
    level: "XII",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "9",
    title: "Pakistan Studies XII (English)",
    author: "Prof. James Miller",
    description:"Detailed biology book for grade XII covering human anatomy, genetics, evolution, and plant sciences with diagrams and exercises.",
    coverImage:"https://mastercoachingcenter.com/assets/images/pakistan12.jfif",
    pdfUrl: "/pdfs/academic-writing-skills.pdf",
    category: "Biology",
    level: "XII",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "10",
    title: "Chemistry XI",
    author: "Prof. James Miller",
    description:
      "Comprehensive chemistry guide for grade XI covering key principles of organic, inorganic, and physical chemistry.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/508055262.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/665073576.pdf",
    category: "Chemistry",
    level: "XI",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "11",
    title: "Mathematics XI",
    author: "Prof. James Miller",
    description:
      "Mathematics textbook for grade XI focusing on algebra, trigonometry, and calculus concepts, with step-by-step solutions.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/17724355.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/866632721.pdf",
    category: "Mathematics",
    level: "XI",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "12",
    title: "Biology XI",
    author: "Prof. James Miller",
    description:
      "Biology textbook for grade XI with clear explanations of cell biology, human physiology, and plant anatomy.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/1906338761.PNG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1543645388.pdf",
    category: "Biology",
    level: "XI",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "13",
    title: "Physics XI",
    author: "Prof. James Miller",
    description:
      "Physics textbook for grade XI with foundational lessons on motion, energy, thermodynamics, and basic laws of physics.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/1502217710.PNG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1510132284.pdf",
    category: "Physics",
    level: "XI",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "14",
    title: "Gulzar-E-Urdu XI",
    author: "Prof. James Miller",
    description:
      "An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:
      "https://ebooks.stbb.edu.pk/storage/uploads/books_images/608225154.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1510132284.pdf",
    category: "Urdu",
    level: "XI",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "15",
    title: "Biology IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/2069794387.jpg",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/941344618.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "16",
    title: "Computer Science IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1441448209.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1554569489.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "17",
    title: "My English IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/868750678.PNG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/174152276.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "18",
    title: "Physics IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/622975132.jpg",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1903986337.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "19",
    title: "Math IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1452784081.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/575689126.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "20",
    title: "Chemsitry IX",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1620749291.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1979946399.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "21",
    title: "Islamiyat IX-X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1129776401.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/48215046.pdf",
    category: "Urdu",
    level: "IX",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
     {
    id: "22",
    title: "Biology X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1012741228.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1603807911.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "23",
    title: "Computer Science X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/115009409.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/969288365.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "24",
    title: "Chemsitry X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/797934480.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1346758524.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "25",
    title: "Secondary Stage English X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/1739674047.PNG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/44328497.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "26",
    title: "Physics X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/575393607.JPG",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/1308453384.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "27",
    title: "Math X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/530438481.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/2146432972.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
    {
    id: "28",
    title: "Pak Studies X",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://ebooks.stbb.edu.pk/storage/uploads/books_images/765309191.png",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/615965828.pdf",
    category: "Urdu",
    level: "X",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: false,
    price: 0,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
  {
    id: "29",
    title: "English for Undergraduates",
    author: "Prof. James Miller",
    description:"An Urdu language textbook for grade XI featuring poetry, prose, grammar, and cultural insights.",
    coverImage:"https://oup.com.pk/media/catalog/product/cache/f27410caed2515ebb4812e4debd92ddc/9/7/9780195978049_1.jpg",
    pdfUrl: "https://ebooks.stbb.edu.pk/storage/uploads/books/615965828.pdf",
    category: "Urdu",
    level: "ADS",
    pages: 278,
    rating: 4.8,
    reviews: 934,
    isPaid: true,
    price: 800,
    downloadCount: 2890,
    uploadedDate: "2024-01-25",
  },
];
